### ISSUE TITLE
Implement a function queue

### ISSUE THREAD

**Issue by camwiegert** [camwiegert/baffle#13]
It'd be nice to have a function queue so we can chain delays. That's a pretty common use and setTimeout isn't ideal.

```javascript
baffle('.selector').start().delay(3000).reveal();
```

**Comment by forclan** [comment]
I think you could use a queue to implement this.
each time you add a task, you push a task in the queue.
`baffle('.selector').start().delay(3000).reveal();`will get ['start', 'delay(3000)', 'reaveal'], and use a timer to check the queue every 10ms;

**Comment by eugene-eeo** [comment]
Implementation note: `Array.shift` is **O(n)**. Probably we need a deque, but I'm not sure how badly that will affect performance. With that being said `Array.shift` *should* work fine for small arrays (I think V8 has some optimisation for arrays whose length is <= 5).

**Comment by forclan** [comment]
get it.
I have found a [library](https://github.com/petkaantonov/deque#quick-start)  which implements queue with better performance.

**Comment by camwiegert** [comment]
If we were going to add a queue, I'd be tempted to use some like [d3-queue](https://github.com/d3/d3-queue) instead of anything custom. This is a little off my radar for the time being.
