### ISSUE TITLE
Need a test suite

### ISSUE THREAD

**Issue by camwiegert** [camwiegert/baffle#15]
A small test suite has been part of the plan, but I haven't gotten to it just yet.

**Comment by cilice** [comment]
I'll make a PR for that with [ava](https://github.com/avajs/ava) 😊

**Comment by camwiegert** [comment]
I'd welcome it! I think [src/utils](https://github.com/camwiegert/baffle/blob/master/src/utils.js) and [src/obfuscator](https://github.com/camwiegert/baffle/blob/master/src/obfuscator.js#L8) would both be pretty simple to test.

**Comment by gdad-s-river** [comment]
@cilice, I want to help. I've never done unit testing / testing before other than some very basic tests. I want to learn to do it right.
