### ISSUE TITLE
Document the delay param in baffle.reveal() on Github Pages

### ISSUE THREAD

**Issue by cilice** [camwiegert/baffle#20]
The second param of the [reveal function](https://github.com/camwiegert/baffle/blob/master/src/baffle.js#L93) isn't documented on the website.

**Comment by camwiegert** [comment]
Do you mean [here](https://camwiegert.github.io/baffle/#methods)? I think it's documented everywhere. Did I miss it somewhere?

**Comment by cilice** [comment]
D'uh, I have no idea what I meant now. Closing for now.
