### ISSUE TITLE
async usages and document translation

### ISSUE THREAD

**Issue by HeskeyBaozi** [camwiegert/baffle#27]
Very interested in this javascript library, and I found that it was firmly attached to the `window.setInterval()`.

Ehmmm.. I think it is a liitle slow while running at the browser..
All the methods are called by chain..

I'm wondering if it can be used with Promise or async function(es7)?
just like that
```javascript
// Promiselike
new Baffle('#id')
    .then(start) // with the speed 50ms
    .then(reavel) // with the reavel time 1000ms
    .catch(error => {throw error;});
```

and `each()` can be replaced by 'for-of' loop

(=  ^  =)!
and I'm a college students in China  ... would you mind if I translate the document into Chinese(simplified) :-)
Emm.. this would be very soon...
the partly translated demo is like that
```markdown
# baffle.js
一个用于DOM元素**文本乱码模糊再恢复**的极简JavaScript库

[camwiegert.github.io/baffle](https://camwiegert.github.io/baffle)

> <img src="https://camwiegert.github.io/baffle/assets/images/baffle.js.png" width="500" alt="baffle.js">


- 压缩约 ~1.8kb :zap:
- 没有任何依赖 :tada:
- 支持IE9+ :heavy_check_mark:
```

**Comment by camwiegert** [comment]
Thanks for these thoughts.

I'm not really concerned about the performance of `setInterval` and there is a discussion about `each()` in #21.

As far as the interface, chaining is totally optional so don't feel obligated to use it. And you shouldn't need to use any async control flow on this as nothing is _really_ async. I could see a use case for doing something at the end of a reveal. I'll investigate that.

Yes, please feel free to provide documentation translations!

**Comment by HeskeyBaozi** [comment]
@camwiegert 
: - )
The translations work has been finished  and the Chinese version document  is accessable at [https://github.com/HeskeyBaozi/baffle-docs-cn](https://github.com/HeskeyBaozi/baffle-docs-cn)

Would you mind if I maintain the Chinese version document in my repositoriy !?= w =..
I will appreciate it = w =..
: - )
