### ISSUE TITLE
When do you use baffle?

### ISSUE THREAD

**Issue by likerRr** [camwiegert/baffle#28]
Hi, very nice module, but I can't come up when it could be useful. 

For example I wouldn't prefer to obfuscate sensitive data such way, because nothing can stop a user from code inspection (e.g. from dev. toolse) and manual revealing obfuscated string. And for example if js is disabled, then obfuscating won't be happened at all. 

The solution for sensitive data could be to generate obfuscated string on the server with some kind of private key and then deobfuscate this string with a public key on the client-side by request. But we haven't such ability since `baffle` works only with DOM nodes and it needs additional information for revealing.

The only few cases I can come up are to have nice text animation on appearing or hiding text spoilers.

Could you provide with more real cases?

**Comment by eugene-eeo** [comment]
> The only few cases I can come up are to have nice text animation on appearing or hiding text spoilers.

Exactly. Also you can impress fellow developers with your sick 'decryption' skillz.

**Comment by camwiegert** [comment]
You're right that baffle is **definitely not** a security tool. It's simply a text effect. Your question brings up an important point, though: do we need a disclaimer of some sort in the README?

**Comment by likerRr** [comment]
@camwiegert probably we need, because my first thought were about hiding some promo codes etc. The term "obfuscate" (for me) means to make things more secure.

**Comment by vortechron** [comment]
baffle.js use case: revealing discount/coupon code when user submit their email or something.
