### ISSUE TITLE
Allow spaces to be obfuscated too

### ISSUE THREAD

**Issue by chadupton** [camwiegert/baffle#29]
More of a feature request than an issue... When there's a sentence hidden, the spaces in the sentence are displayed as spaces. It would be nice to have the option to obfuscate the spaces too.

It looks like the inspiration (http://oak.is) does obfuscate spaces.

**Comment by camwiegert** [comment]
@chadupton The default behavior is to exclude spaces, but you can pass an empty array of characters as the [exclude option](https://github.com/camwiegert/baffle#optionsexclude) too. Hope that helps!

```js
// Default behavior
b.set({
    exclude: [' ']
})

// Don't exclude spaces
b.set({
    exclude: []
})
```
