### ISSUE TITLE
Baffle bugs when scrolling

### ISSUE THREAD

**Issue by carloswbarros** [camwiegert/baffle#31]
When I click a link that scrolls the page or scroll the page clicking on the scrollbar and not releasing the cursor, baffle bugs and doesn't finish the effect. 

You can test it on my website: https://carloswbarros.github.io/

The source code is here: https://github.com/carloswbarros/personal-website-source/blob/master/static/js/app.js#L88

Gif of the problem: http://g.recordit.co/DQvw2ar3pI.gif (sorry for the slow gif :p)

**Comment by camwiegert** [comment]
@carloswbarros I took a look at the source and I suspect this is what's happening: the callback you're passing to `$.fn.appear` is being called multiple times and, so, baffle is getting initialized multiple times on the same element.

So, if the text hasn't been fully revealed and baffle initializes again, it thinks the partially obfuscated text is the source text. Hope this helps!

```js
var b = baffle('.baffle', {
    characters: '█▓▒░█▓▒░█▓▒░<>/',
    speed: 70
});

$('.baffle').appear(function() {
    setTimeout( function(){ // the timeout is me trying to async this
        b.reveal(900);
    }, 0);
});
```

**Comment by carloswbarros** [comment]
You are right, it seems to be working now. Thanks for the help ;)
