### ISSUE TITLE
feat: add option for different resolve directions

### ISSUE THREAD

**Issue by janriemer** [camwiegert/baffle#32]
Hey @camwiegert,

First of all, really awesome library! I love it! :heart:

I thought we could add an option for the direction in which the text resolves (currently it resolves randomly), like so (possible values are separated by `|`):
## Example

``` javascript
baffle('.baffle', {
    resolveDirection: 'begin-end | end-begin | inside-out | outside-in | none'
});
```
## Specification of the values
- _begin-end_: starts resolving at the beginning of the string and makes it's way through 'til the end.
  - alternative naming: `left-right`
- _end-begin_: opposite of `begin-end`
- _inside-out_: starts resolving at the middle of the string and consecutively resolves towards the beginning/end of the string
- _outside-in_: opposite of `inside-out`
- _none_(default): this is the resolve algorithm we have now (resolve randomly)
  - alternative naming: `random` <- problem: could be confused with "select one `resolveDirection` randomly"

Do you have any ideas/improvements on this?
I'd love to create a PR for this!  :wink:

**Comment by camwiegert** [comment]
@janriemer Interesting idea! I'd imagine that we could just pass a resolve strategy argument to [decay](https://github.com/camwiegert/baffle/blob/master/src/obfuscator.js#L61) and handle it there.

Regarding semantics, I'd be tempted to name the option `resolveFrom` and have the options be: 
- `left`
- `right`
- `inside`
- `outside`
- `random`

I'd welcome a PR for it. One consideration is that `Obfuscator` is pretty simple and low-level right now, and I wouldn't want to introduce too much complexity. Just a heads up. Thanks! 👍
