### ISSUE TITLE
support .html() on the string

### ISSUE THREAD

**Issue by sandrina-p** [camwiegert/baffle#36]
`baffleFoo.text(currentText => "hello <i>world</i>");`

This will output this:

`hello <i>world</i>`

But I want this:

hello _world_

Is there any option on your script to support .html() ? 

Thank you :)

**Comment by akimad** [comment]
+1

**Comment by camwiegert** [comment]
@sandrina-p Currently, baffle operates on `node.textContent`. To allow what you're asking, we'd have to recursively walk through any child elements and operate on their text individually. That will make things significantly more complicated, but I'd welcome PRs and ideas for how to make this work without a major overhaul. Thanks!

**Comment by QuadDepo** [comment]
Hey,

I just came across this awesome lib and was also looking for this feature. I did took a look the source code but feel my knowledge is just to little to contribute and add this. 

I did some searching and I know Typed.js uses this; https://github.com/mattboldt/typed.js/blob/6f3c0686106f570d42a5b3152b789444a44dfba8/src/html-parser.js
