### ISSUE TITLE
Possible to use multiple fonts in baffle characters?

### ISSUE THREAD

**Issue by z-a-h** [camwiegert/baffle#37]
I see that you can exclude certain characters from being obfuscated, however I was wondering if it's possible to use two different font's for the characters in `options.fonts`.

Right now I'm using the array of characters from the example, `["█", "▓", "▒", "░", "█", "▓", "▒", "░", "█", "▓", "▒", "░"]` however I'd also like to include a single letter, but use a different from other characters as the unicode shade characters look ugly in the font i'm using for the letter.

**Comment by camwiegert** [comment]
@z-a-h Sorry for the late answer! That's something you'd probably want to handle with CSS. This library will only determine the characters used, not the fonts.
