### ISSUE TITLE
GIF Maker

### ISSUE THREAD

**Issue by vilbht** [camwiegert/baffle#42]
Hello

Love the finesse on Baffle! Noob Q: Any ideas on how to approach the creation of a GIF tool that can output the animated baffle text in a div?

**Comment by ajsnyde** [comment]
Found out about Baffle an hour ago. Why would you want this, rather than just running it? Why not just record a gif of it running and then embed it?

**Comment by vilbht** [comment]
@ajsnyde the intent was to let non-savvy users create their own GIFs and export them as per a specific design spec in terms of size and timing length

**Comment by camwiegert** [comment]
Going to close this as it's out of scope.
