### ISSUE TITLE
How would I go about using this library via Vue?

### ISSUE THREAD

**Issue by swwwnsn** [camwiegert/baffle#43]
I've tried `
import baffle from 'baffle';
let b = baffle('#baffled');
b.start();
` but it doesn't do anything at all.

**Comment by junip** [comment]
@swwwnsn  It is working fine for me.
for further help you can refer to my repo https://github.com/Junip551/Vue-baffle

**Comment by creatpix103** [comment]
Hi, I'm trying to use this in a [Nuxt](https://nuxtjs.org/) setup, but when I tried to import it in / as plugin I've this error... 

![image](https://user-images.githubusercontent.com/36721764/50449264-2e45c680-094c-11e9-855d-77eff000354d.png)

and here's import...

![image](https://user-images.githubusercontent.com/36721764/50449298-6a792700-094c-11e9-94f0-8c2ef07c7931.png)

**Comment by junip** [comment]
@creatpix103  After installing baffle you can directly use baffle, just you need to import it as you have already done. you dont need to use like Vue.use(baffle).
you can look into the implementation in my repo https://github.com/Junip551/Vue-baffle
