### ISSUE TITLE
How to reveal baffle animation when element is in view?

### ISSUE THREAD

**Issue by kulbhushanchand** [camwiegert/baffle#45]
Hi,
The baffle animation starts whether the element to be animated is in viewport or not. 
Is it possible to reveal animation when element is in view?

**Comment by louh** [comment]
Try using the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). There is a [polyfill](https://github.com/w3c/IntersectionObserver) for older browsers.
